### ISSUE TITLE
Pointer provenance issue

### ISSUE THREAD

**Issue by Plecra** [stjepang/polling#21]
https://github.com/stjepang/polling/blob/f4ee76fb322e0b67ee84b2dcc863fed4d6a9b107/src/epoll.rs#L195

Aiui this is technically UB at the moment, and you need to use `buf.as_ptr()` instead. Practically, I don't think this is worth treating as unsound, but it wouldn't hurt to fix.

https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=c4baca7337e045758b01422f4c322dfc

**Comment by stjepang** [comment]
Fixed in v2.0.2, thanks!
