### ISSUE TITLE
Way to register sockets without Oneshot

### ISSUE THREAD

**Issue by matheuslessarodrigues** [stjepang/polling#4]
I don't know if this is some kind of restriction on the api because of the underlying implementations,
but it would be really nice to get updates on sockets without needing to re-register them everytime.

In my usecase, wait and registering are done from different threads so it's not possible to just re-register a socket when
an event is received.

This issue asside, this is exactly the crate I was looking for to use with Unix Domain Sockets even when on windows!

**Comment by stjepang** [comment]
Note that wepoll only supports oneshot and level-triggering modes: https://github.com/piscisaureus/wepoll#features

This unfortunately rules out edge-triggering mode, which is probably what you'd want.

In `async-io` crate, I get around the issue you mention by grabbing a lock when re-registering sockets.

**Comment by matheuslessarodrigues** [comment]
You're right! I indeed wanted edge-triggering mode.
The reason the previous code was working is that I was using a Barrier so I would only wall `poll` again after every event was handled. I've refactored the code to support reregistering and removed the barriers. It works now!

Thanks for the support
